@startuml
'========================
' SEÇÃO 1 - Includes
'========================
' utils
!include <aws/common>

' Armazenamento
!include <aws/Storage/AmazonS3/AmazonS3>
!include <aws/Storage/AmazonS3/bucket/bucket>
!include <aws/Database/AmazonDynamoDB/AmazonDynamoDB>

' Computação
!include <aws/Compute/AWSLambda/AWSLambda>

' Integração
!include <aws/ApplicationServices/AmazonAPIGateway/AmazonAPIGateway>

'========================
' SEÇÃO 2 - Definição de participantes
'========================
actor "Usuário"
AMAZONS3(s3,"Bucket XPTO")
AMAZONAPIGATEWAY(apiGateway, "API XPTO")
AMAZONDYNAMODB(dynamoDB, "Tabela XPTO")
AWSLAMBDA(lambda, "Função XPTO") /' rectangle "Minha função" as Lambda <<$AWSLambda>>'/

'========================
' SEÇÃO 3 - Agrupamentos (opcional)
'========================
' package "Backend AWS" {
'   apiGateway
'   lambda
'   s3
'   dynamoDB
' }

'========================
' SEÇÃO 4 - Relacionamentos
'========================
"Usuário" -> apiGateway
apiGateway -> lambda
lambda --> dynamoDB : CRUD
lambda --> s3 : Salva dados para analytics

'========================
' SEÇÃO 5 - Notas (opcional)
'========================
note right of lambda
  A Lambda pode:
  - Validar entrada
  - Gravar no S3
  - Atualizar estado no Dynamo
end note

@enduml